#https://docs.netlify.com/configure-builds/overview/
#https://docs.netlify.com/configure-builds/overview/
[build]
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"